http:
  routers:
    portainer-http:
      rule: "Host(`portainer.homelab.internal`)"
      entryPoints:
        - web
      middlewares:
        - portainer-redirect-https
      service: portainer-service

    portainer-https:
      rule: "Host(`portainer.homelab.internal`)"
      entryPoints:
        - websecure
      middlewares:
        - authentik@file
      tls: {}
      service: portainer-service

    code-http:
      rule: "Host(`code.homelab.internal`)"
      entryPoints:
        - web
      middlewares:
        - code-redirect-https
      service: code-service

    code-https:
      rule: "Host(`code.homelab.internal`)"
      entryPoints:
        - websecure
      middlewares:
        - authentik@file
      tls: {}
      service: code-service

    scrypted-http:
      rule: "Host(`scrypted.homelab.internal`)"
      entryPoints:
        - web
      middlewares:
        - scrypted-redirect-https
      service: scrypted-service

    scrypted-https:
      rule: "Host(`scrypted.homelab.internal`)"
      entryPoints:
        - websecure
      tls: {}
      service: scrypted-service

    tautulli-http:
      rule: "Host(`tautulli.homelab.internal`)"
      entryPoints:
        - web
      middlewares:
        - tautulli-redirect-https
      service: tautulli-service

    tautulli-https:
      rule: "Host(`tautulli.homelab.internal`)"
      entryPoints:
        - websecure
      middlewares:
        - authentik@file
      tls: {}
      service: tautulli-service

    homeassistant-http:
      rule: "Host(`homeassistant.homelab.internal`)"
      entryPoints:
        - web
      middlewares:
        - homeassistant-redirect-https
      service: homeassistant-service

    homeassistant-https:
      rule: "Host(`homeassistant.homelab.internal`)"
      entryPoints:
        - websecure
      tls: {}
      service: homeassistant-service

    myspeed-http:
      rule: "Host(`myspeed.homelab.internal`)"
      entryPoints:
        - web
      middlewares:
        - myspeed-redirect-https
      service: myspeed-service

    myspeed-https:
      rule: "Host(`myspeed.homelab.internal`)"
      entryPoints:
        - websecure
      middlewares:
        - authentik@file
      tls: {}
      service: myspeed-service

    prowlarr-http:
      rule: "Host(`prowlarr.homelab.internal`)"
      entryPoints:
        - web
      middlewares:
        - prowlarr-redirect-https
      service: prowlarr-service

    prowlarr-https:
      rule: "Host(`prowlarr.homelab.internal`)"
      entryPoints:
        - websecure
      middlewares:
        - authentik@file
      tls: {}
      service: prowlarr-service

    flaresolverr-http:
      rule: "Host(`flaresolverr.homelab.internal`)"
      entryPoints:
        - web
      middlewares:
        - flaresolverr-redirect-https
      service: flaresolverr-service

    flaresolverr-https:
      rule: "Host(`flaresolverr.homelab.internal`)"
      entryPoints:
        - websecure
      middlewares:
        - authentik@file
      tls: {}
      service: flaresolverr-service

    tools-http:
      rule: "Host(`tools.homelab.internal`)"
      entryPoints:
        - web
      middlewares:
        - tools-redirect-https
      service: tools-service

    tools-https:
      rule: "Host(`tools.homelab.internal`)"
      entryPoints:
        - websecure
      middlewares:
        - authentik@file
      tls: {}
      service: tools-service

    pdf-http:
      rule: "Host(`pdf.homelab.internal`)"
      entryPoints:
        - web
      middlewares:
        - pdf-redirect-https
      service: pdf-service

    pdf-https:
      rule: "Host(`pdf.homelab.internal`)"
      entryPoints:
        - websecure
      middlewares:
        - authentik@file
      tls: {}
      service: pdf-service

    glances-http:
      rule: "Host(`glances.homelab.internal`)"
      entryPoints:
        - web
      middlewares:
        - glances-redirect-https
      service: glances-service

    glances-https:
      rule: "Host(`glances.homelab.internal`)"
      entryPoints:
        - websecure
      middlewares:
        - authentik@file
      tls: {}
      service: glances-service

  middlewares:
    portainer-redirect-https:
      redirectScheme:
        scheme: https
        permanent: true

    code-redirect-https:
      redirectScheme:
        scheme: https
        permanent: true

    scrypted-redirect-https:
      redirectScheme:
        scheme: https
        permanent: true

    tautulli-redirect-https:
      redirectScheme:
        scheme: https
        permanent: true

    homeassistant-redirect-https:
      redirectScheme:
        scheme: https
        permanent: true

    myspeed-redirect-https:
      redirectScheme:
        scheme: https
        permanent: true

    prowlarr-redirect-https:
      redirectScheme:
        scheme: https
        permanent: true

    flaresolverr-redirect-https:
      redirectScheme:
        scheme: https
        permanent: true

    glances-redirect-https:
      redirectScheme:
        scheme: https
        permanent: true

    tools-redirect-https:
      redirectScheme:
        scheme: https
        permanent: true

    pdf-redirect-https:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    portainer-service:
      loadBalancer:
        serversTransport: portainer-transport
        servers:
          - url: "https://192.168.20.69:9443"

    code-service:
      loadBalancer:
        servers:
          - url: "http://192.168.20.69:8443"

    scrypted-service:
      loadBalancer:
        serversTransport: scrypted-transport
        servers:
          - url: "https://192.168.20.69:10443"

    tautulli-service:
      loadBalancer:
        servers:
          - url: "http://192.168.20.69:8181"

    homeassistant-service:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "http://192.168.20.69:8123"

    myspeed-service:
      loadBalancer:
        servers:
          - url: "http://192.168.20.2:5216"

    prowlarr-service:
      loadBalancer:
        servers:
          - url: "http://192.168.20.69:9696"

    flaresolverr-service:
      loadBalancer:
        servers:
          - url: "http://192.168.20.69:8191"

    tools-service:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "http://192.168.20.2:7190"

    pdf-service:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "http://192.168.20.2:7890"

    glances-service:
      loadBalancer:
        servers:
          - url: "http://192.168.20.69:61208"

  serversTransports:
    portainer-transport:
      insecureSkipVerify: true

    scrypted-transport:
      insecureSkipVerify: true
