http:
  routers:
    plex-http:
      rule: "Host(`plex.homelab.internal`)"
      entryPoints:
        - web
      middlewares:
        - plex-redirect-https
      service: plex-service

    plex-https:
      rule: "Host(`plex.homelab.internal`)"
      entryPoints:
        - websecure
      tls: {}
      service: plex-service

  middlewares:
    plex-redirect-https:
      redirectScheme:
        scheme: https

  services:
    plex-service:
      loadBalancer:
        servers:
          - url: "http://192.168.20.69:32400"
