services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8888:8080"  # Traefik dashboard on :8888
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dynamic:/etc/traefik/dynamic:ro
    environment:
      TZ: Australia/Sydney
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.homelab`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.routers.traefik.entrypoints=web
    networks:
      - traefik
      - arrnetwork

networks:
  traefik:
    name: traefik
    driver: bridge
  arrnetwork:
    name: arrnetwork
    external: true
